In [5]:
import pandas as pd
import numpy as np

# 1.Version of NumPy
print(np.__version__)
print(pd.__version__)

1.23.3
1.4.4


In [9]:
df = pd.read_csv('data.csv')

# 2.Number of records in the dataset
df.shape

(11914, 16)

In [10]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [12]:
#  3.The most popular car manufacturers
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [15]:
# 4.number of unique Audi car models

len(df[df['Make']=='Audi']['Model'].unique())

34

In [20]:
#  5.Number of columns with missing values
df.info() #5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [23]:
# 6.Does the median value change after filling missing values?

print(df['Engine Cylinders'].median())
print(df['Engine Cylinders'].value_counts())
print(df['Engine Cylinders'].fillna(4).median())


6.0
4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64
6.0


In [76]:
# 7.Value of the first element of w

lotus_df = df[df['Make']=='Lotus'][['Engine HP', 'Engine Cylinders']].copy()
print(lotus_df.shape)

lotus_df=lotus_df.drop_duplicates()
print(lotus_df.shape)

print('underlying NumPy')
X = lotus_df.values

print(X)

print('matrix-matrix multiplication between the transpose of X and X')
XTX = x.T.dot(x)
print(XTX)

print('Invert XTX')
XTX_inv = np.linalg.inv(XTX) 
print(XTX_inv)

print('create array')
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

print(y)

print('Multiply the inverse of XTX with the transpose of X, and then multiply the result by y')
w = XTX_inv.dot(X.T).dot(y)

w[0]


(29, 2)
(9, 2)
underlying NumPy
[[189.   4.]
 [218.   4.]
 [217.   4.]
 [350.   8.]
 [400.   6.]
 [276.   6.]
 [345.   6.]
 [257.   4.]
 [240.   4.]]
matrix-matrix multiplication between the transpose of X and X
[[7.31684e+05 1.34100e+04]
 [1.34100e+04 2.52000e+02]]
Invert XTX
[[ 5.53084235e-05 -2.94319825e-03]
 [-2.94319825e-03  1.60588447e-01]]
create array
[1100  800  750  850 1300 1000 1000 1300  800]
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y


4.594944810094551